In [1]:
import pandas as pd 
import numpy as np

### Recognizing missing data

In [3]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, np.nan, 30],         # Bob's Age is missing
    'Salary': [50000, 60000, np.nan] # Charlie's Salary is missing
})

# 1. The Mask (Hard to read for big data)
print(df.isnull())

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True

In [4]:
# 2. The Count (The Standard Way)
print("Missing values per column:")
print(df.isnull().sum())

Missing values per column:
Name      0
Age       1
Salary    1
dtype: int64

#### Handling Missing Data

#### Removing NaN values

In [5]:
import pandas as pd

# Original DataFrame
print("Original DataFrame:")
print(df)
print("-" * 50)

# Remove ANY row that contains at least one NaN
clean_rows = df.dropna()
print("After dropping rows with ANY NaN:")
print(clean_rows)
print("-" * 50)

# Remove ANY column that contains at least one NaN
clean_cols = df.dropna(axis=1)
print("After dropping columns with ANY NaN:")
print(clean_cols)
print("-" * 50)

# Smart drop: Remove rows ONLY if 'Name' is NaN
# (Keeps rows where other columns like Age may be NaN)
smart_drop = df.dropna(subset=["Name"])
print("After dropping rows where 'Name' is NaN:")
print(smart_drop)
print("-" * 50)

Original DataFrame:
      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob   NaN  60000.0
2  Charlie  30.0      NaN
--------------------------------------------------
After dropping rows with ANY NaN:
    Name   Age   Salary
0  Alice  25.0  50000.0
--------------------------------------------------
After dropping columns with ANY NaN:
      Name
0    Alice
1      Bob
2  Charlie
--------------------------------------------------
After dropping rows where 'Name' is NaN:
      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob   NaN  60000.0
2  Charlie  30.0      NaN
--------------------------------------------------

In [6]:
# 1. Fill with Zero (Good for things like 'Debt' or 'Points')
df_zero = df.fillna(0)
print("After filling NaN values with 0 ")
print(df_zero)
print("-" * 50)

After filling NaN values with 0
      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob   0.0  60000.0
2  Charlie  30.0      0.0
--------------------------------------------------

#### Statistical Imputation

In [ ]:
print("Before filling NaN in Age:")
print(df)
print("-" * 50)

mean_age = df["Age"].mean()
print(f"Mean Age: {mean_age}")
print("-" * 50)

# Fill NaN values in Age with the mean
df["Age"] = df["Age"].fillna(mean_age)

# After filling NaN
print("After filling NaN in Age with mean:")
print(df)
print("-" * 50)

# forward and backward fill
print("Before forward fill:")
print(df)
print("-" * 50)

# Forward fill (propagate last valid observation forward)
df_ffill = df.fillna(method='ffill')
print("After forward fill:")
print(df_ffill)
print("-" * 50)
# Backward fill (propagate next valid observation backward)
df_bfill = df.fillna(method='bfill')
print("After backward fill:")
print(df_bfill)
print("-" * 50)

Before filling NaN in Age:
      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob   NaN  60000.0
2  Charlie  30.0      NaN
--------------------------------------------------
Mean Age: 27.5
--------------------------------------------------
After filling NaN in Age with mean:
      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob  27.5  60000.0
2  Charlie  30.0      NaN
--------------------------------------------------

### Handling Duplicates

In [ ]:
import pandas as pd

# Sample Dataset with Duplicates
data = {
    'TransactionID': [101, 102, 101, 103],
    'Amount': [500, 750, 500, 200]
}
df = pd.DataFrame(data)
print(df)
print("-" * 50)
# Step 1: Identification (Returns Boolean Truth Values)
# True = This row is a duplicate of a previous row
print(f'Which rows are duplicates?')
print(df.duplicated())

# Step 2: Quantification (Counting Errors)
# Summing the boolean values (True=1, False=0)
duplicate_count = df.duplicated().sum()
print(f"Total Duplicate Rows: {duplicate_count}")
print("-" * 50)

# Step 3: Cleaning (The 'Set' Operation)
# 'inplace=True' modifies the actual table instead of creating a copy
df.drop_duplicates(inplace=True)

# Verification
print(df)

   TransactionID  Amount
0            101     500
1            102     750
2            101     500
3            103     200
--------------------------------------------------
Which rows are duplicates?
0    False
1    False
2     True
3    False
dtype: bool
Total Duplicate Rows: 1
--------------------------------------------------
   TransactionID  Amount
0            101     500
1            102     750
3            103     200

### Detecting Outliers

$$Z = \frac{X - \mu}{\sigma}$$

In [10]:
import pandas as pd

print("STEP 1: Create sample salary data")
print("-" * 50)

df = pd.DataFrame({'Salary': [48, 50, 52, 49, 51, 53, 47, 34, 41, 22, 93, 72, 10, 45, 88, 1, 170]})

print("Original Data:")
print(df)
print("\n")

STEP 1: Create sample salary data
--------------------------------------------------
Original Data:
    Salary
0       48
1       50
2       52
3       49
4       51
5       53
6       47
7       34
8       41
9       22
10      93
11      72
12      10
13      45
14      88
15       1
16     170

In [11]:
print("STEP 2: Compute statistical properties")
print("-" * 50)

# Mean (μ): central tendency
mean_salary = df['Salary'].mean()

# Standard deviation (σ): spread of the data
std_dev = df['Salary'].std()

print(f"Mean (μ) Salary      : {mean_salary:.2f}")
print(f"Std Deviation (σ)    : {std_dev:.2f}")
print("\n")

STEP 2: Compute statistical properties
--------------------------------------------------
Mean (μ) Salary      : 54.47
Std Deviation (σ)    : 37.92

In [12]:
print("STEP 3: Define the Safe Zone using the 3-Sigma Rule")
print("-" * 50)

upper_limit = mean_salary + (3 * std_dev)
lower_limit = mean_salary - (3 * std_dev)

print(f"Lower Limit (μ - 3σ): {lower_limit:.2f}")
print(f"Upper Limit (μ + 3σ): {upper_limit:.2f}")
print("\n")

STEP 3: Define the Safe Zone using the 3-Sigma Rule
--------------------------------------------------
Lower Limit (μ - 3σ): -59.30
Upper Limit (μ + 3σ): 168.24

In [13]:
df.head()

   Salary
0      48
1      50
2      52
3      49
4      51

In [20]:
print("STEP 4: Remove values outside the Safe Zone (Outliers)")
print("-" * 50)



# df_lower=df[
#     (df['Salary']>lower_limit)
# ]
# print(df_lower)

# df_lower_upper=df_lower[
#     (df_lower['Salary'] < upper_limit)
# ]
# print(df_lower_upper)



#                  or



# Keep only values within the defined boundaries
df_clean = df[
    (df['Salary'] > lower_limit) &
    (df['Salary'] < upper_limit)
]
print("Cleaned Data (Outliers Removed):")
print(df_clean)




#             using or
# Keep only values within the defined boundaries
# df_clean = df[
#     (df['Salary'] > lower_limit) |
#     (df['Salary'] < upper_limit)
# ]

# print("Cleaned Data (Outliers Removed):")
# print(df_clean)

STEP 4: Remove values outside the Safe Zone (Outliers)
--------------------------------------------------
Cleaned Data (Outliers Removed):
    Salary
0       48
1       50
2       52
3       49
4       51
5       53
6       47
7       34
8       41
9       22
10      93
11      72
12      10
13      45
14      88
15       1
16     170

#### Extreme Outliers

In [23]:
import pandas as pd

df = pd.DataFrame({
    'Salary': [48, 50, 52, 49, 51, 53, 10_000_000]
})
df

     Salary
0        48
1        50
2        52
3        49
4        51
5        53
6  10000000

In [24]:
mu = df['Salary'].mean()
sigma = df['Salary'].std()
print(f'Mean: {mu}, Standard Deviation: {sigma}')
print("-" * 50)

lower = mu - 3*sigma
upper = mu + 3*sigma

print(f"3σ Range: {lower:.2f} to {upper:.2f}")
print("-" * 50)

print(df[(df['Salary'] > lower) & (df['Salary'] < upper)])

Mean: 1428614.7142857143, Standard Deviation: 3779625.642886771
--------------------------------------------------
3σ Range: -9910262.21 to 12767491.64
--------------------------------------------------
     Salary
0        48
1        50
2        52
3        49
4        51
5        53
6  10000000

Here, 3-sigma rule fails. 
Extreme value remains.

Thus, we need inter-quartile range for better handling of such extreme outliers.

#### Inter-quartile Range

In [25]:
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

print(f"IQR Range: {lower:.2f} to {upper:.2f}")
print(df[(df['Salary'] >= lower) & (df['Salary'] <= upper)])

IQR Range: 45.00 to 57.00
   Salary
0      48
1      50
2      52
3      49
4      51
5      53

### Data Transformation, Normalization and Type Conversion

In [26]:
import pandas as pd

# ----------------------------
# Sample dataset (raw data)
# ----------------------------
df = pd.DataFrame({
    'Gender': ['Male', 'Female', 'Male'],   # Nominal categorical
    'Risk': ['Low', 'High', 'Medium'],     # Ordinal categorical
    'Age': ['25', '45', '30']              # Numeric stored as strings
})

print("Original Data:")
print(df)
print("\n")

# ----------------------------
# 1. Categorical Encoding (Nominal)
# ----------------------------
# Gender is nominal: no order
# Mapping text to integers using dictionary (Unit V: Key-Value)
gender_map = {'Male': 0, 'Female': 1}
df['Gender_encoded'] = df['Gender'].map(gender_map)

print("After Categorical Encoding (Nominal - Gender):")
print(df[['Gender', 'Gender_encoded']])
print("\n")

# ----------------------------
# 2. Ordinal Encoding
# ----------------------------
# Risk is ordinal: Low < Medium < High
# Mapping preserves order
risk_map = {'Low': 0, 'Medium': 1, 'High': 2}
df['Risk_encoded'] = df['Risk'].map(risk_map)

print("After Ordinal Encoding (Risk):")
print(df[['Risk', 'Risk_encoded']])
print("\n")

Original Data:
   Gender    Risk Age
0    Male     Low  25
1  Female    High  45
2    Male  Medium  30


After Categorical Encoding (Nominal - Gender):
   Gender  Gender_encoded
0    Male               0
1  Female               1
2    Male               0


After Ordinal Encoding (Risk):
     Risk  Risk_encoded
0     Low             0
1    High             2
2  Medium             1

In [27]:

# ----------------------------
# 3. Type Conversion
# ----------------------------
# Age is numeric but stored as string
# Convert to integer for computation
df['Age'] = df['Age'].astype(int)

print("After Type Conversion (Age):")
print(df[['Age']])
print("\n")

# ----------------------------
# 4. Normalization (Min-Max Scaling)
# ----------------------------
# Scale Age to [0,1] range
df['Age_norm'] = (df['Age'] - df['Age'].min()) / (df['Age'].max() - df['Age'].min())

print("After Normalization (Age):")
print(df[['Age', 'Age_norm']])
print("\n")

# ----------------------------
# Final DataFrame
# ----------------------------
print("Final DataFrame with all transformations applied:")
print(df)

After Type Conversion (Age):
   Age
0   25
1   45
2   30


After Normalization (Age):
   Age  Age_norm
0   25      0.00
1   45      1.00
2   30      0.25


Final DataFrame with all transformations applied:
   Gender    Risk  Age  Gender_encoded  Risk_encoded  Age_norm
0    Male     Low   25               0             0      0.00
1  Female    High   45               1             2      1.00
2    Male  Medium   30               0             1      0.25

In [ ]:
# 1. Who’s Weird? (Z-Score Ranking)
# • Compute z-scores for values
# • Rank items by how unusual they are
# • Label: Normal / Unusual / Extreme
# 2. Before vs After Normalization
# • Normalize data using z-score and min-max
# • Compare rankings before and after scaling
# 3. Feature Variability Ranking
# • Rank columns by standard deviation
# • Identify low-variance features
# 4. Design Your Own Dataset
# • Create a real-life numeric dataset
# • Normalize and summarize the data
# • Explain results in plain language